services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: tena360
      POSTGRES_USER: tena360
      POSTGRES_PASSWORD: tena360
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate && python manage.py seed_foods && gunicorn tena360.wsgi:application --bind 0.0.0.0:8000"

volumes:
  postgres_data:
